### ISSUE TITLE
bitcoin hacker

### ISSUE THREAD

**Issue by i0t4** [LocalsGitHub/Decrypt-Discord-Token#1]
my bitcoins got hacked do not use

**Comment by LocalsGitHub** [comment]
Bro how

**Comment by LocalsGitHub** [comment]
How did you know

**Comment by i0t4** [comment]
They hacked all of my bitcoins and they got transferred to `hackerbitcoinblockchainfortnite35.eth`

**Comment by LocalsGitHub** [comment]
Bro
