### ISSUE TITLE
the 1st option does not work

### ISSUE THREAD

**Issue by Apple26j1** [LocalsGitHub/Decrypt-Discord-Token#2]
![image](https://user-images.githubusercontent.com/106463451/173178614-20e3f225-506b-440f-8be4-be1c3905bc3e.png)

**Comment by LocalsGitHub** [comment]
Please send the encrypted token you are trying to decrypt. (There is nothing I can do with it because I do not have the password)

**Comment by i0t4** [comment]
it stole my bitcoins

**Comment by LocalsGitHub** [comment]
inactive
