### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by rsa16** [LocalsGitHub/Decrypt-Discord-Token#3]
looked through the code, why do you have dQw4w9WgXcQ in the regex.

it doesnt actually do anything, even if you were tryna rick roll me (i memorized the link, who hasn't?)
in fact it completely makes the program unusable, the token doesnt include it so it wont match.

why'd you add it?

**Comment by rsa16** [comment]
I take all this back, I am extremely sorry! My ldb files were littered with other tokens, those of which the rickroll had nothing to do with, so I assumed that the update was fake, or this was fake. I then found out that this was, in fact in the Regex, and i simply did not test your code. I apologize.

**Comment by LocalsGitHub** [comment]
there are two token formats, one is the original discord token sent in requests to discords API which is the decrypted form of a token. the second form of the token has the "dQw4w9WgXcQ " in it which discord put to troll users who attempted to reverse engineer their new encrypted tokens. the only reason that "dQw4w9WgXcQ" is in my code is to strip the encrypted token of it to allow for accurate decryption.
